version: '3'
services:
  server:
    image: bigbutton-server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - 8011:3000

#  app:
#    image: bigbutton-app
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    volumes:
#     - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    ports:
#     - "8011:80"

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: unless-stopped
    ports: 
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080