version: '3'
services:
  server:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app:cached
      - /var/run/docker.sock:/var/run/docker.sock 
    command: /bin/sh -c "while sleep 1000; do :; done"
 
